name: Lean CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  head_build:
    name: Fast head check (lean quick checks)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install elan (Lean toolchain)
        shell: bash
        run: |
          set -euxo pipefail
          curl -sSfL https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | bash -s -- -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - name: Cache Lake packages
        uses: actions/cache@v4
        with:
          path: ./.lake/packages
          key: ${{ runner.os }}-lake-${{ hashFiles('lake-manifest.json') }}
          restore-keys: |
            ${{ runner.os }}-lake-
      - name: Slice monolith head and run quick checks
        shell: bash
        run: |
          set -euxo pipefail
          source $HOME/.elan/env
          cp IndisputableMonolith.lean IndisputableMonolith.full.lean
          head -n 6000 IndisputableMonolith.full.lean > IndisputableMonolith.lean
          lake update
          lake env -- lean -q IndisputableMonolith/Core.lean -o /dev/null
          lake env -- lean -q IndisputableMonolith.lean -o /dev/null
          lake exe ci_checks | sed -e 's/.*/HEAD: &/'
      - name: CI guard (no sorry/admit, report axiom count)
        shell: bash
        run: |
          set -euxo pipefail
          chmod +x scripts/ci_guard.sh
          ./scripts/ci_guard.sh

  full_quick:
    name: Full quick checks (lean) — allow failure
    runs-on: ubuntu-latest
    needs: head_build
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install elan (Lean toolchain)
        shell: bash
        run: |
          set -euxo pipefail
          curl -sSfL https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | bash -s -- -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - name: Cache Lake packages
        uses: actions/cache@v4
        with:
          path: ./.lake/packages
          key: ${{ runner.os }}-lake-${{ hashFiles('lake-manifest.json') }}
          restore-keys: |
            ${{ runner.os }}-lake-
      - name: Run lean quick checks on full monolith
        shell: bash
        run: |
          set -euxo pipefail
          source $HOME/.elan/env
          lake update
          lake env -- lean -q IndisputableMonolith/Core.lean -o /dev/null
          lake env -- lean -q IndisputableMonolith.lean -o /dev/null
          lake exe ci_checks | sed -e 's/.*/FULL: &/'
      - name: CI guard (no sorry/admit, report axiom count)
        shell: bash
        run: |
          set -euxo pipefail
          chmod +x scripts/ci_guard.sh
          ./scripts/ci_guard.sh
