name: Fast CI (cached head build)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: fast-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  head_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install elan (Lean toolchain)
        shell: bash
        run: |
          set -euxo pipefail
          curl -sSfL https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | bash -s -- -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Cache lake artifacts
        uses: actions/cache@v4
        with:
          path: |
            .lake
            lake-packages
            build
          key: ${{ runner.os }}-lake-${{ hashFiles('**/lake-manifest.json') }}
          restore-keys: |
            ${{ runner.os }}-lake-

      - name: Update deps
        run: |
          source $HOME/.elan/env
          lake update

      - name: Head-only build (first 6000 lines)
        shell: bash
        run: |
          set -euxo pipefail
          source $HOME/.elan/env
          cp IndisputableMonolith.lean IndisputableMonolith.full.lean
          head -n 6000 IndisputableMonolith.full.lean > IndisputableMonolith.lean
          lake build IndisputableMonolith
          git checkout -- IndisputableMonolith.lean || cp IndisputableMonolith.full.lean IndisputableMonolith.lean

      - name: Run CI checks
        run: |
          source $HOME/.elan/env
          lake exe ci_checks


